print("Post Lab")
print("Question 1")
n, z = sp.symbols('n z')
x_n = 3**n
X_z = sp.summation(x_n * z**(-n), (n, 0, sp.oo))
print("Z-Transform of x[n] = 3^n u[n]:")
sp.pprint(X_z, use_unicode=True)
print("\nQuestion 2")
n, z, omega = sp.symbols('n z omega')
x_n = sp.cos(omega * n)
X_z = sp.summation(x_n * z**(-n), (n, 0, sp.oo))
print("Z-Transform of x[n] = cos(ωn) u[n]:")
sp.pprint(X_z, use_unicode=True)
